application_name = "codepipeline-packer-build"
sns_endpoint     = "XXX@test.de"
aws_kms_alias                       = "terraform-state-storage"
tf_state_storage_bucket_name        = "terraform-state-storage"
tf_state_storage_dynamodb_lock_name = "terraform-state-storage"