instance_type = "t2.micro"
region = "eu-central-1"
source_ami_name = "ubuntu/images/hvm-ssd/ubuntu-*-amd64-server-*"
source_ami_owner = "099720109477"
packer_image_ssh_username = "ubuntu"
packer_image_name = "learn-packer"
